services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
